steps:
 # Build the container image
 -  name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/the-slate-133223/github.com/united-states-pirate-party-cooperative/k8s-alpine-drupal:$REVISION_ID', '.']
    timeout: 500s
 # Push the container image to Container Registry
 -  name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/the-slate-133223/github.com/united-states-pirate-party-cooperative/k8s-alpine-drupal:$REVISION_ID']
 # deploy container image to GKE
 -  name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/my-deployment', 'gcr.io/the-slate-133223/github.com/united-states-pirate-party-cooperative/k8s-alpine-drupal:$REVISION_ID']
timeout: 3600s
