apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  app: drupal-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: drupal-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: drupal-app
    spec:
      containers:
      - image: gcr.io/the-slate-133223/united-states-pirate-party-cooperative/k8s-alpine-drupal:$REVISION_ID
        securityContext:
          capabilities:
            add: ["SYS_ADMIN", "SETPCAP"]
        imagePullPolicy: IfNotPresent
        name: k8s-alpine-drupal-sha256-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - message: ReplicaSet "drupal9-77cf9574b8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
---
apiVersion: v1
kind: Service
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  clusterIP: None
  selector:
    app: drupal-app
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: drupal-app
spec:
  selector:
    matchLabels:
      app: drupal # has to match .spec.template.metadata.labels
  serviceName: "drupal"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: drupal # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: drupal
        image: gcr.io/the-slate-133223/united-states-pirate-party-cooperative/k8s-alpine-drupal:$REVISION_ID
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        volumeMounts:
        - name: www1
          mountPath: /var/www1
  volumeClaimTemplates:
  - metadata
    - name: www-us-central1-a-claim
      namespace: default
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: ''
      resources:
        requests:
          storage: 1T
