apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-06-30T21:40:01Z"
  generation: 1
  labels:
    app: drupal9
  name: drupal9
  namespace: default
  resourceVersion: "5750747"
  selfLink: /apis/apps/v1/namespaces/default/deployments/drupal9
  uid: 95e796ea-1fe8-4695-a184-f2407c72e10e
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: drupal9
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: drupal9
    spec:
      containers:
      - image: gcr.io/the-slate-133223/k8s-alpine-drupal@sha256:cfd88b8168d8ba66f37830473f0be8b4c99e194b11a57019868393b17b5521b3
        securityContext:
          capabilities:
            add: ["SYS_ADMIN", "SETPCAP"]
        imagePullPolicy: IfNotPresent
        name: k8s-alpine-drupal-sha256-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2020-06-30T21:40:23Z"
    lastUpdateTime: "2020-06-30T21:40:23Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-06-30T21:40:01Z"
    lastUpdateTime: "2020-06-30T21:40:23Z"
    message: ReplicaSet "drupal9-77cf9574b8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
