apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: drupal-app
  name: drupal-app
spec:
  replicas: 3
  selector:
    matchLabels:
      run: drupal-app
  template:
    metadata:
      labels:
        run: drupal-app
    spec:
      containers:
      - image: gcr.io/$PROJECT_ID/drupal-app:latest
        name: drupal-app
        ports:
        - containerPort: 9000
